from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from hms_backend.app.core.database import get_db
from hms_backend.app.utils.generic_crud import get_generic_records, create_generic_record, delete_generic_record

router = APIRouter(prefix="/reports", tags=["reports"])


@router.get("")
def get_reports_summary(db: Session = Depends(get_db)):
    defaults = [
        {"id": 1, "Report Name": "Monthly Patient Flow Analysis", "Generated By": "Admin Bot", "Date": "2026-08-13", "Type": "Operational"},
        {"id": 2, "Report Name": "Pharmacy Revenue Audit Q2", "Generated By": "Vikram Singh", "Date": "2026-08-05", "Type": "Financial"},
    ]
    return get_generic_records(db, "admin_reports", defaults)

@router.post("")
def create_report(payload: dict, db: Session = Depends(get_db)):
    return create_generic_record(db, "admin_reports", payload)

@router.delete("/{record_id}")
def delete_report(record_id: int, db: Session = Depends(get_db)):
    return delete_generic_record(db, "admin_reports", record_id)
